name: freeflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  jwt_decoder:
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  permission_handler: ^11.3.0
  get: ^4.6.6
  flutter_map_location_marker: ^8.0.8
  geocoding: ^2.2.1
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mongo_dart: ^0.10.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/google.jpg
  - lib/images/apple.jpg
  - lib/images/shelter.svg
  - lib/images/foodBank.svg
